language: go
go:
- 1.11.x
env:
- GO111MODULE=on
script:
- go build .
deploy:
  provider: releases
  api_key:
    secure: aJTx20VVPktZ9DpUv6XtSMmxbv6IaJOBd1DR1aFpmGO8zfbuezwAvzbm3KcDWV11WD9Jov4ktDduG/dj3I5xCSRFix5DKbxlC/gabLkg5wAoooPbYdgSD0Pz2GsIuS7bmHWHU8F+KKp8E6XFhhotmB3mmpe2tx4OYVpr+bxb7cLOK/J2y04VpjVME/Ok1JoH9Iro/cypb8GZ3SEBSbEfyFQvQUTiAyb3bLuHYBZ8VqAAQFXDYCY/ivclOEE09K0Ezb+33uon2JE7Dt0Nm9is0ve4hWDj2wn39mhQ+g+pxqSH+y+31KXy4v84YGFZiVIZgaDrQSaymXSlo809U4rYuWjMoQ2xxI9JYa3DfPEYU6jSDBEZ24Bx4xl0MvAe8x+ncQY8yNevs6ovszQGA3fEhUxfP4LK7sKqQpAwFAOT+86k4Rm4CG8jG/CqiejzxEPkYTF5o8z1bSfBuHFompXrlmnDoPuBfx1aevtz6mezNgLmTeDk75ZfPgUh2QLxnDbbl9cjoF30WJGXRgVvW58syG/1iHBSZH0fkmVq66dvvZu7y2Lsb179Mo8lyKyo5khJFYNpW1RrDxjtXMLLpYML7Fr4rEkJQjviJ23TouaabtSh9JNfI+AZ11/WLaQOLjwcu9NcCeMwSdDFV66Xgwau30lnyjOiEVpgxUhmZmDsBnA=
  file: gomodtutorial
  on:
    repo: eexe1/go-module-example
